const config = require('../config');

const stats = {
    users : [
        config.testUser,
        {
            userId: 'peopleId1',
            birthday: 1943,
            job: 1,
            gender: 'male',
        },
        {
            userId: 'peopleId2',
            birthday: 1989,
            job: 1,
            gender: 'female',
        },
        {
            userId: 'peopleId3',
            birthday: 1990,
            job: 2,
            gender: 'male',
        },
        {
            userId: 'uninstalledOldPeople',
            birthday: 1970,
            job: 1,
            gender: 'male',
        }
        ],
    appUsages : [
        ////////// start of me ///////////////
        {
            date: new Date('2019-04-11T00:00:00.000Z'),
            userId: config.testUser.userId,
            packageName: 'com.nhn.android.nmap',
            totalUsedTime: 9999,
            appName: '네이버지도',
            categoryId: 'TOOL',
            categoryName: '도구',
            developer: 'NHN Corp.',
            iconUrl: 'iconUrl0',
            gender: 'male',
            birthday: 1992,
            job: 1,
        }, {
        // 특정 앱의 사용 데이터는 있지만 해당 앱 정보가 DB에 없는 경우, 해당 앱은 제외한다.
        date: new Date('2019-04-11T00:00:00.000Z'),
        userId: config.testUser.userId,
        packageName: 'com.game.empty',
        totalUsedTime: 10000,
        gender: 'male',
        birthday: 1992,
        job: 1,
    }, {
        date: new Date('2019-04-11T00:00:00.000Z'),
        userId: config.testUser.userId,
        packageName: 'com.game.edu',
        totalUsedTime: 90000,
        appName: '교육게임명',
        categoryId: 'GAME_EDUCATIONAL',
        categoryName: '교육',
        developer: 'Edu Game Corp.',
        iconUrl: 'iconUrl3',
        gender: 'male',
        birthday: 1992,
        job: 1,
    }, {
        date: new Date('2019-04-14T00:00:00.000Z'),
        userId: config.testUser.userId,
        packageName: 'com.game.rpg',
        totalUsedTime: 10000,
        appName: '롤플레잉게임명',
        categoryId: 'GAME_ROLE_PLAYING',
        categoryName: '롤플레잉',
        developer: 'GameDuckHu Corp.',
        iconUrl: 'iconUrl4',
        gender: 'male',
        birthday: 1992,
        job: 1,
    }, {
        date: new Date('2019-04-19T00:00:00.000Z'),
        userId: config.testUser.userId,
        packageName: 'com.game.edu2',
        totalUsedTime: 5000,
        appName: '교육게임명2',
        categoryId: 'GAME_EDUCATIONAL',
        categoryName: '교육',
        developer: 'GameDuckHu Corp.',
        iconUrl: 'iconUrl32',
        gender: 'male',
        birthday: 1992,
        job: 1,
    }, {
        date: new Date('2019-04-15T00:00:00.000Z'),
        userId: config.testUser.userId,
        packageName: 'com.game.edu2',
        totalUsedTime: 4000,
        appName: '교육게임명2',
        categoryId: 'GAME_EDUCATIONAL',
        categoryName: '교육',
        developer: 'GameDuckHu Corp.',
        iconUrl: 'iconUrl32',
        gender: 'male',
        birthday: 1992,
        job: 1,
    },
        ////////// end of me ///////////////
        {
            date: new Date('2019-04-11T00:00:00.000Z'),
            userId: 'peopleId1',
            packageName: 'com.game.edu2',
            totalUsedTime: 7000,
            appName: '교육게임명2',
            categoryId: 'GAME_EDUCATIONAL',
            categoryName: '교육',
            developer: 'GameDuckHu Corp.',
            iconUrl: 'iconUrl32',
            birthday: 1943,
            job: 1,
            gender: 'male',
        }, {
        date: new Date('2019-04-19T00:00:00.000Z'),
        userId: 'peopleId1',
        packageName: 'com.game.rpg',
        totalUsedTime: 4000,
        appName: '롤플레잉게임명',
        categoryId: 'GAME_ROLE_PLAYING',
        categoryName: '롤플레잉',
        developer: 'GameDuckHu Corp.',
        iconUrl: 'iconUrl4',
        birthday: 1943,
        job: 1,
        gender: 'male',
    }, {
        date: new Date('2019-04-11T00:00:00.000Z'),
        userId: 'peopleId2',
        packageName: 'com.game.rpg',
        totalUsedTime: 90000,
        appName: '롤플레잉게임명',
        categoryId: 'GAME_ROLE_PLAYING',
        categoryName: '롤플레잉',
        developer: 'GameDuckHu Corp.',
        iconUrl: 'iconUrl4',
        birthday: 1989,
        job: 1,
        gender: 'female',
    }, {
        date: new Date('2019-04-19T00:00:00.000Z'),
        userId: 'peopleId2',
        packageName: 'com.game.puzzle',
        totalUsedTime: 10000,
        appName: '퍼즐게임명',
        categoryId: 'GAME_PUZZLE',
        categoryName: '퍼즐',
        developer: 'Puzzle Game Corp.',
        iconUrl: 'iconUrl6',
        birthday: 1989,
        job: 1,
        gender: 'female',
    }, {
        date: new Date('2019-04-11T00:00:00.000Z'),
        userId: 'peopleId3',
        packageName: 'com.game.edu',
        totalUsedTime: 100000,
        appName: '교육게임명',
        categoryId: 'GAME_EDUCATIONAL',
        categoryName: '교육',
        developer: 'Edu Game Corp.',
        iconUrl: 'iconUrl3',
        birthday: 1990,
        job: 2,
        gender: 'male',
    }, {
        date: new Date('2019-04-19T00:00:00.000Z'),
        userId: 'peopleId3',
        packageName: 'com.game.puzzle',
        totalUsedTime: 50000,
        appName: '퍼즐게임명',
        categoryId: 'GAME_PUZZLE',
        categoryName: '퍼즐',
        developer: 'Puzzle Game Corp.',
        iconUrl: 'iconUrl6',
        birthday: 1990,
        job: 2,
        gender: 'male',
    }, {
        // 특정 앱의 사용 데이터는 있지만 비정규화 이전 버전 앱 사용으로 categoryId가 AppUsages에 없는 경우, 해당 앱은 제외한다.
        userId: 'uninstalledOldPeople',
        packageName: 'com.game.puzzle',
        totalUsedTime: 7777777777
    }],
    apps : [
        {
            packageName: 'com.nhn.android.nmap',
            appName: '네이버지도',
            categoryId1: 'TOOL',
            categoryName1: '도구',
            developer: 'NHN Corp.',
            iconUrl: 'iconUrl0',
        }, {
        packageName: 'com.game.edu',
        appName: '교육게임명',
        categoryId1: 'GAME_EDUCATIONAL',
        categoryName1: '교육',
        developer: 'Edu Game Corp.',
        iconUrl: 'iconUrl3',
    }, {
        packageName: 'com.game.rpg',
        appName: '롤플레잉게임명',
        categoryId1: 'GAME_ROLE_PLAYING',
        categoryName1: '롤플레잉',
        developer: 'GameDuckHu Corp.',
        iconUrl: 'iconUrl4',
    }, {
        packageName: 'com.game.edu2',
        appName: '교육게임명2',
        categoryId1: 'GAME_EDUCATIONAL',
        categoryName1: '교육',
        developer: 'GameDuckHu Corp.',
        iconUrl: 'iconUrl32',
    }, {
        packageName: 'com.game.puzzle',
        appName: '퍼즐게임명',
        categoryId1: 'GAME_PUZZLE',
        categoryName1: '퍼즐',
        developer: 'Puzzle Game Corp.',
        iconUrl: 'iconUrl6',
    }],
};
const recommend = {
    recommendAppUsages: [
        {
            // 특정 앱의 사용 데이터는 있지만 해당 앱 정보가 DB에 없는 경우, 해당 앱은 제외한다.
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: config.testUser.userId,
            packageName: 'com.game.empty',
            totalUsedTime: 10000,
            gender: 'male',
            birthday: 1992,
            job: 1,
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: config.testUser.userId,
            packageName: 'com.game.edu',
            totalUsedTime: 90000,
            gender: 'male',
            birthday: 1992,
            job: 1,
            developer: 'Edu Game Corp.',
            categoryId: 'GAME_EDUCATIONAL',
            categoryName: '교육',
            iconUrl: 'iconUrl3',
            appName: '교육게임명',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: config.testUser.userId,
            packageName: 'com.game.rpg',
            totalUsedTime: 10000,
            gender: 'male',
            birthday: 1992,
            job: 1,
            developer: 'GameDuckHu Corp.',
            categoryId: 'GAME_ROLE_PLAYING',
            categoryName: '롤플레잉',
            iconUrl: 'iconUrl4',
            appName: '롤플레잉게임명',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: config.testUser.userId,
            packageName: 'com.game.edu2',
            totalUsedTime: 5000,
            gender: 'male',
            birthday: 1992,
            job: 1,
            developer: 'GameDuckHu Corp.',
            categoryId: 'GAME_EDUCATIONAL',
            categoryName: '교육',
            iconUrl: 'iconUrl32',
            appName: '교육게임명2',
        },
////////// end of me ///////////////
        {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId1',
            packageName: 'com.game.edu2',
            totalUsedTime: 7000,
            birthday: 1943,
            job: 1,
            gender: 'male',
            developer: 'GameDuckHu Corp.',
            categoryId: 'GAME_EDUCATIONAL',
            categoryName: '교육',
            iconUrl: 'iconUrl32',
            appName: '교육게임명2',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId1',
            packageName: 'com.game.rpg',
            totalUsedTime: 4000,
            birthday: 1943,
            job: 1,
            gender: 'male',
            developer: 'GameDuckHu Corp.',
            categoryId: 'GAME_ROLE_PLAYING',
            categoryName: '롤플레잉',
            iconUrl: 'iconUrl4',
            appName: '롤플레잉게임명',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId2',
            packageName: 'com.game.rpg',
            totalUsedTime: 90000,
            birthday: 1989,
            job: 1,
            gender: 'female',
            developer: 'GameDuckHu Corp.',
            categoryId: 'GAME_ROLE_PLAYING',
            categoryName: '롤플레잉',
            iconUrl: 'iconUrl4',
            appName: '롤플레잉게임명',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId2',
            packageName: 'com.game.puzzle',
            totalUsedTime: 10000,
            birthday: 1989,
            job: 1,
            gender: 'female',
            developer: 'Puzzle Game Corp.',
            categoryId: 'GAME_PUZZLE',
            categoryName: '퍼즐',
            iconUrl: 'iconUrl6',
            appName: '퍼즐게임명',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId3',
            packageName: 'com.game.edu',
            totalUsedTime: 100000,
            birthday: 1990,
            job: 2,
            gender: 'male',
            developer: 'Edu Game Corp.',
            categoryId: 'GAME_EDUCATIONAL',
            categoryName: '교육',
            iconUrl: 'iconUrl3',
            appName: '교육게임명',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId3',
            packageName: 'com.game.edu4',
            totalUsedTime: 3000,
            birthday: 1990,
            job: 2,
            gender: 'male',
            developer: 'GameDuckHu Corp.',
            categoryId: 'GAME_EDUCATIONAL',
            categoryName: '교육',
            iconUrl: 'iconUrl33',
            appName: '교육게임명4',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId4',
            packageName: 'com.game.edurpg',
            totalUsedTime: 300,
            birthday: 2000,
            job: 1,
            gender: 'female',
            developer: 'Edu Game Corp.',
            categoryId: 'GAME_ROLE_PLAYING',
            categoryName: '롤플레잉',
            iconUrl: 'iconUrl3',
            appName: '교육RPG',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId3',
            packageName: 'com.game.puzzle',
            totalUsedTime: 50000,
            birthday: 1990,
            job: 2,
            gender: 'male',
            developer: 'Puzzle Game Corp.',
            categoryId: 'GAME_PUZZLE',
            categoryName: '퍼즐',
            iconUrl: 'iconUrl6',
            appName: '퍼즐게임명',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId3',
            packageName: 'com.game.edurpg',
            totalUsedTime: 2000,
            birthday: 1990,
            job: 2,
            gender: 'male',
            developer: 'Edu Game Corp.',
            categoryId: 'GAME_ROLE_PLAYING',
            categoryName: '롤플레잉',
            iconUrl: 'iconUrl3',
            appName: '교육RPG',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId5',
            packageName: 'com.game.edurpg',
            totalUsedTime: 45000,
            birthday: 1995,
            job: 1,
            gender: 'male',
            developer: 'Edu Game Corp.',
            categoryId: 'GAME_ROLE_PLAYING',
            categoryName: '롤플레잉',
            iconUrl: 'iconUrl3',
            appName: '교육RPG',
        }, {
            date: new Date('2019-04-19T00:00:00.000Z'),
            userId: 'peopleId5',
            packageName: 'com.game.edu3',
            totalUsedTime: 15000,
            birthday: 1995,
            job: 1,
            gender: 'male',
            developer: 'GameDuckHu Corp.',
            categoryId: 'GAME_EDUCATIONAL',
            categoryName: '교육',
            iconUrl: 'iconUrl33',
            appName: '교육게임명3',
        },
        /** 여기서부터는 7일 이상 넘은 데이터들 **/
        {
            date: new Date('1900-04-01T00:00:00.000Z'),
            userId: 'peopleId3',
            packageName: 'com.game.edurpg',
            totalUsedTime: 2000,
            birthday: 1990,
            job: 2,
            gender: 'male',
            developer: 'Edu Game Corp.',
            categoryId: 'GAME_ROLE_PLAYING',
            categoryName: '롤플레잉',
            iconUrl: 'iconUrl3',
            appName: '교육RPG',
        }, {
            date: new Date('1900-04-01T00:00:00.000Z'),
            userId: 'peopleId5',
            packageName: 'com.game.edurpg',
            totalUsedTime: 45000,
            birthday: 1995,
            job: 1,
            gender: 'male',
            developer: 'Edu Game Corp.',
            categoryId: 'GAME_ROLE_PLAYING',
            categoryName: '롤플레잉',
            iconUrl: 'iconUrl3',
            appName: '교육RPG',
        }, {
            date: new Date('1900-04-01T00:00:00.000Z'),
            userId: 'peopleId5',
            packageName: 'com.game.edu3',
            totalUsedTime: 15000,
            birthday: 1995,
            job: 1,
            gender: 'male',
            developer: 'GameDuckHu Corp.',
            categoryId: 'GAME_EDUCATIONAL',
            categoryName: '교육',
            iconUrl: 'iconUrl33',
            appName: '교육게임명3',
        }]
};

module.exports = { stats, recommend };